# Generated by Django 4.2.6 on 2023-10-20 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('company_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('internship', 'Internship'), ('other', 'Other')], max_length=20)),
                ('industry_category', models.CharField(choices=[('IT', 'Information Technology'), ('Healthcare', 'Healthcare'), ('Finance', 'Finance'), ('Education', 'Education')], default='IT', max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job_requirements', models.TextField()),
                ('education_requirements', models.CharField(max_length=50)),
                ('experience_level', models.CharField(max_length=20)),
                ('contact_information', models.CharField(max_length=100)),
                ('benefits', models.TextField()),
                ('skills_and_qualities', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RecruiterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='Company Full Name')),
                ('gst_no', models.CharField(max_length=15, verbose_name='GSTIN Number')),
                ('gst_doc', models.FileField(upload_to='gst_documents/', verbose_name='Upload GST Document')),
                ('email_id', models.EmailField(max_length=254, unique=True, verbose_name='Email Id')),
                ('mobile_number', models.BigIntegerField(verbose_name='Mobile Number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_recruiter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recruiter',
                'verbose_name_plural': 'Recruiters',
                'permissions': [('can_view_recruiter_custom', 'Can View Recruiter Custom')],
            },
        ),
        migrations.CreateModel(
            name='JobSeekerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Id')),
                ('mobile_number', models.BigIntegerField(verbose_name='Mobile Number')),
                ('work_experience', models.CharField(choices=[('Fresher', 'Fresher'), ('Experienced', 'Experienced')], max_length=20, verbose_name='Work Experience')),
                ('resume', models.FileField(upload_to='resumes/', verbose_name='Resume')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_seeker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Seeker',
                'verbose_name_plural': 'Job Seekers',
                'permissions': [('can_view_job_seekers_custom', 'Can View Job Seekers Custom')],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='app.job')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobseekermodel')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='applicants',
            field=models.ManyToManyField(blank=True, related_name='applied_jobs', to='app.jobseekermodel'),
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
