# Generated by Django 4.2.6 on 2023-10-31 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_aboutmodel_postaboutmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='updated_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='company_image',
            field=models.ImageField(null=True, upload_to='company_images/', verbose_name='Company Image'),
        ),
        migrations.AddField(
            model_name='postaboutmodel',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='postaboutmodel',
            name='updated_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='type',
            field=models.CharField(choices=[('Is JobSeeker', 'Is JobSeeker'), ('Is JobRecruiter', 'Is JobRecruiter')], max_length=20),
        ),
    ]
