# Generated by Django 4.2.6 on 2023-10-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_jobseekermodel_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekermodel',
            name='profile_image',
            field=models.ImageField(default='profile_images/default-profile_H0hvU91.png', upload_to='profile_images/', verbose_name='Profile Image'),
        ),
    ]
