# Generated by Django 4.2.6 on 2023-10-31 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_contactmodel_created_at_contactmodel_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Delhi', 'Delhi'), ('Mumbai', 'Mumbai'), ('Pune', 'Pune'), ('Bangalore', 'Bangalore'), ('Gurgaon', 'Gurgaon'), ('Hyderabad', 'Hyderabad'), ('Chennai', 'Chennai'), ('Kolkata', 'Kolkata'), ('Ahmedabad', 'Ahmedabad'), ('Jaipur', 'Jaipur'), ('Lucknow', 'Lucknow'), ('Noida', 'Noida'), ('Chandigarh', 'Chandigarh'), ('Kochi', 'Kochi'), ('Indore', 'Indore'), ('Surat', 'Surat'), ('Vadodara', 'Vadodara'), ('Coimbatore', 'Coimbatore'), ('Bhubaneswar', 'Bhubaneswar'), ('Nagpur', 'Nagpur'), ('Patna', 'Patna'), ('Mysore', 'Mysore'), ('Visakhapatnam', 'Visakhapatnam'), ('Goa', 'Goa')], default='Delhi', max_length=100)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
