# Generated by Django 4.2.6 on 2023-10-31 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='location',
        ),
        migrations.AddField(
            model_name='location',
            name='location_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
