# Generated by Django 4.2.6 on 2023-10-25 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_jobseekermodel_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='recuiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recuiter', to='app.recruitermodel'),
        ),
    ]
